# Generated by Django 4.0.4 on 2022-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('logitude', models.FloatField()),
            ],
        ),
    ]
